version: '3.4'

services:
  backend:
    build:
      context: ./apps
      dockerfile: ./backend/Dockerfile
    ports:
      - '8080:8080'
    working_dir: /app/apps/backend
    volumes:
      - .:/app:rw,cached
    depends_on: 
      - postgres
    networks:
      - webnet

  frontend:
    build:
      context: ./apps
      dockerfile: ./frontend/Dockerfile
    ports:
      - '3000:3000'
    working_dir: /app/apps/frontend
    volumes:
      - .:/app:rw,cached
    networks:
      - webnet

  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - webnet
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=abcd0123

networks:
  webnet:

volumes:
  database-data: